#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Class-Method-Modifiers
Version  : 2.13
Release  : 14
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Method-Modifiers-2.13.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Method-Modifiers-2.13.tar.gz
Summary  : 'Provides Moose-like method modifiers'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Class-Method-Modifiers-license = %{version}-%{release}
Requires: perl-Class-Method-Modifiers-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Needs)
BuildRequires : perl(Test::Requires)
BuildRequires : perl(Try::Tiny)

%description
This archive contains the distribution Class-Method-Modifiers,
version 2.13:
Provides Moose-like method modifiers

%package dev
Summary: dev components for the perl-Class-Method-Modifiers package.
Group: Development
Provides: perl-Class-Method-Modifiers-devel = %{version}-%{release}
Requires: perl-Class-Method-Modifiers = %{version}-%{release}

%description dev
dev components for the perl-Class-Method-Modifiers package.


%package license
Summary: license components for the perl-Class-Method-Modifiers package.
Group: Default

%description license
license components for the perl-Class-Method-Modifiers package.


%package perl
Summary: perl components for the perl-Class-Method-Modifiers package.
Group: Default
Requires: perl-Class-Method-Modifiers = %{version}-%{release}

%description perl
perl components for the perl-Class-Method-Modifiers package.


%prep
%setup -q -n Class-Method-Modifiers-2.13
cd %{_builddir}/Class-Method-Modifiers-2.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Class-Method-Modifiers
cp %{_builddir}/Class-Method-Modifiers-2.13/LICENSE %{buildroot}/usr/share/package-licenses/perl-Class-Method-Modifiers/0ee97faea3c205afafb52e3f0418b2e261abcf99
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Class::Method::Modifiers.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Class-Method-Modifiers/0ee97faea3c205afafb52e3f0418b2e261abcf99

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.1/Class/Method/Modifiers.pm
